---
jobs:
- name: Dynamic secuirty scan
  plan:
    - task: dynamic-security-scan
      file: rft-sdp-ZAP-SAM/tasks/dast.yml
      input_mapping: {source-code: rft-sdp-ZAP-SAM, pipeline: pipeline-pipeline.yml}
    