---
  resources:
    - name: pipeline-git
      type: git
      icon: git
      source:
        uri:  https://github.com/sumeet-kumar-rft/rft-sdp-ZAP-SAM.git
        branch: SAM
        username: ((github_access_token))
        password: x-oauth-basic   

  jobs:
  - name: ZAP-demo-scan
    plan:
    - get: pipeline-git
      trigger: true
    - task: dynamic-security-scan
      file: pipeline-git/tasks/dast2.yml
      params:
        TARGET_URL: http://zero.webappsecurity.com
        context-path: ${PWD}/pipeline-git/tasks/zero.webappsecurity.com.context