---
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: owasp/zap2docker-stable
              tag: latest
          outputs:
            - name: output
          run:
            user: root
            path: bash
            args:
              - "-c"
              - |
                apt-get update && apt-get install -q -y --fix-missing jq
                pip install --upgrade pip && pip install --upgrade zapcli
                zap-cli start --start-options '-config api.disablekey=true'
                zap-cli -v active-scan --spider --ajax-spider --scanners all "http://demo.testfire.net" || true
                zap-cli shutdown

                #cd /tmp
                #set -o monitor
                #trap `exit(0)` CHLD
                #/zap/zap-baseline.py -t http://demo.testfire.net
                #kill `pgrep Xvfb`
                #echo "DAST SCANNING COMPLETE"
                