---
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: owasp/zap2docker-stable
              tag: latest
          inputs:
            - name: pipeline-git
          outputs:
            - name: output
          run:
            user: root
            path: bash
            args:
              - "-c"
              - |
                ls
                apt-get update && apt-get install -q -y --fix-missing jq
                pip install --upgrade pip && pip install --upgrade zapcli
                zap-cli start --start-options '-config api.disablekey=true'
                zap-cli context import pipeline-git/tasks/DefaultContext2.context
                zap-cli open-url http://demo.testfire.net
                zap-cli spider http://demo.testfire.net
                zap-cli -v active-scan --scanners all --recursive http://demo.testfire.net
                zap-cli alerts
                zap-cli shutdown

                #cd /tmp
                #set -o monitor
                #trap `exit(0)` CHLD
                #/zap/zap-baseline.py -t http://demo.testfire.net
                #kill `pgrep Xvfb`
                #echo "DAST SCANNING COMPLETE"
                