---
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: owasp/zap2docker-stable
              tag: latest
          inputs:
            - name: pipeline-git
            # this is new line u have added to fetch from the context file for login and remove line 23 
          outputs:
            - name: output
          run:
            user: root
            path: bash
            args:
              - "-c"
              - |
                set -euxo pipefail
                #ls -al
                #cd ${PWD}/pipeline-git/tasks/
                #ls -al pipeline-git/tasks/
                pwd; ls -al pipeline-git/tasks
                apt-get update && apt-get install -q -y --fix-missing jq
                pip install --upgrade pip && pip install --upgrade zapcli
                zap-cli start --start-options '-config api.disablekey=true'
                #ls -al ${PWD}/pipeline-git/tasks/target-data/payload.json
                #cp DefaultContext2.context /${PWD}/pipeline-git/tasks/
                #cd ${PWD}/pipeline-git/tasks/target-data/
                #zap-cli context export --name DefaultContext2 --file-path ${PWD}/DefaultContext2.context
                zap-cli context import ${PWD}/pipeline-git/tasks/zero.webappsecurity.com.context
                zap-cli open-url http://zero.webappsecurity.com
                zap-cli spider -c zero.webappsecurity.com -u username http://zero.webappsecurity.com
                #zap-cli ajax-spider -c zero.webappsecurity.com -u username http://zero.webappsecurity.com
                zap-cli -v active-scan --scanners all --recursive -c zero.webappsecurity.com -u username http://zero.webappsecurity.com
                zap-cli alerts
                #echo $?
                zap-cli shutdown

                #cd /tmp
                #set -o monitor
                #trap `exit(0)` CHLD
                #/zap/zap-baseline.py -t http://demo.testfire.net
                #kill `pgrep Xvfb`
                #echo "DAST SCANNING COMPLETE"
                