---
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: owasp/zap2docker-stable
              tag: latest
          outputs:
            - name: output
          run:
            path: bash
            args:
              - "-c"
              - |
                cd /tmp
                set -o monitor
                trap `exit(0)` CHLD
                /zap/zap-baseline.py -t http://demo.testfire.net 
                kill `pgrep Xvfb`
                echo "DAST SCANNING COMPLETE"
      
